# Generated by Django 3.2.12 on 2022-08-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Группа')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление подготовки')),
                ('profile', models.CharField(default='-', max_length=100, verbose_name='Профиль | Специализация')),
                ('level', models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура')], default='Бакалавриат', max_length=15, verbose_name='Уровень обучения')),
                ('code', models.CharField(max_length=10, verbose_name='Шифр направления')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['level', 'code'],
            },
        ),
    ]
