# Generated by Django 3.2.12 on 2022-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
