# Generated by Django 3.2.12 on 2023-01-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['level', 'code', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
