# Generated by Django 3.2.12 on 2022-08-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='groupsubject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subjects.groupsubject', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='result',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Студент'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('students', 'groupsubject')},
        ),
    ]
