# Generated by Django 3.2.12 on 2022-08-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['group', 'semester', 'last_name'], 'verbose_name': 'Студенты', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='result',
            name='tag',
            field=models.CharField(blank=True, choices=[('СЗ', 'СЗ')], default='', max_length=10, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.CharField(blank=True, choices=[('из АО', 'из АО'), ('восстановлен', 'восстановлен'), ('перевелся на фак-т', 'перевелся на фак-т'), ('перевелся с фак-та', 'перевелся с фак-та')], default='', max_length=25, verbose_name='Тэг'),
        ),
    ]
