# Generated by Django 3.2.12 on 2023-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Зачетная книжка'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.CharField(blank=True, choices=[('из АО', 'из АО'), ('восстановлен', 'восстановлен'), ('перевелся на фак-т', 'перевелся на фак-т'), ('перевелся с фак-та', 'перевелся с фак-та'), ('целевой', 'целевой')], db_index=True, default='', max_length=25, verbose_name='Тэг'),
        ),
    ]
