# Generated by Django 3.2.12 on 2022-08-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubject',
            options={'ordering': ['groups_id', 'subjects'], 'verbose_name': 'Назначения дисциплин', 'verbose_name_plural': 'Назначения дисциплин'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'semester', 'name', '-form_control', 'cathedra', 'att_date'], 'verbose_name': 'Дисциплины', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Сокращение (аббревиатура)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(blank=True, default='', help_text='Фамилия И.О.', max_length=150, verbose_name='Преподаватель'),
        ),
    ]
