# Generated by Django 3.2.12 on 2022-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20220819_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubject',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
