# Generated by Django 3.2.12 on 2022-09-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20220820_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Сокращение'),
        ),
        migrations.AlterUniqueTogether(
            name='cathedra',
            unique_together={('name', 'short_name', 'faculty')},
        ),
    ]
