# Generated by Django 3.2.12 on 2022-09-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20220902_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathedra',
            options={'ordering': ['name'], 'verbose_name': 'Кафедры', 'verbose_name_plural': 'Кафедры'},
        ),
    ]
