# Generated by Django 3.2.12 on 2022-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_cathedra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='zet',
            field=models.CharField(blank=True, default='', help_text='72 (2)', max_length=15, verbose_name='ЗЕТ'),
        ),
    ]
