# Generated by Django 3.2.12 on 2023-01-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_tag'),
        ('subjects', '0007_auto_20221109_1837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'form_control', 'semester', 'cathedra')},
        ),
    ]
