# Generated by Django 3.2.12 on 2023-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsubject',
            unique_together=set(),
        ),
    ]
