# Generated by Django 3.2.12 on 2023-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_groupsubject_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='comment',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='groupsubject',
            name='teacher',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Фамилия И.О.', max_length=150, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Дисциплина'),
        ),
    ]
