# Generated by Django 3.2.12 on 2023-07-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20230616_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cathedra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='subjects.cathedra', verbose_name='Кафедра'),
            preserve_default=False,
        ),
    ]
